FROM golang:1.26-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download || true

COPY . .
RUN go mod tidy

RUN CGO_ENABLED=0 go build -o /out/api ./cmd/api

FROM alpine:3.20

WORKDIR /app

COPY --from=build /out/api /app/api
COPY web/static /app/web/static

EXPOSE 8080
ENTRYPOINT ["/app/api"]

